name: Playwright Tests After Production Deploy

on:
  push:
    branches:
      - main

jobs:
  check-vercel-status:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel deployment
        run: |
          VERCEL_TOKEN="8pWfMU3up740lRADSs1m9bzJ"
          DEPLOYMENT_URL="https://www.devslearning.com"

          while true; do
            STATUS=$(curl -s "https://api.vercel.com/v8/projects/deployments?url=${DEPLOYMENT_URL}" -H "Authorization: Bearer ${VERCEL_TOKEN}" | jq -r '.deployments[0].state')
            if [ "$STATUS" == "READY" ]; then
              echo "Deployment is ready!"
              break
            else
              echo "Waiting for deployment to complete..."
              sleep 30
            fi
          done

  test:
    runs-on: ubuntu-latest
    needs: check-vercel-status
    steps:
      - name: Set environment variable for baseURL
        run: echo "DOMAIN=https://www.devslearning.com" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
